version: '3.8'

services:
  # TruthScan Application
  truthscan:
    image: truthscan:latest
    container_name: truthscan-app
    ports:
      - "5001:5001"
    environment:
      # API Keys (from .env file)
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - KNOWLEDGE_GRAPH_API_KEY=${KNOWLEDGE_GRAPH_API_KEY}
      - MEDIASTACK_API_KEY=${MEDIASTACK_API_KEY}
      - GNEWS_API_KEY=${GNEWS_API_KEY}
      # Configuration
      - TRUTHSCAN_MODE=${TRUTHSCAN_MODE:-balanced}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3